package game.league.trofeocuarentena.services;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import game.league.trofeocuarentena.entities.Leagues;

/**contiene las interfaces que extienden de JPA para que estas clases se conecten 
 * a la base de datos. Estas gestionan información ya sea de buscar, borrar, actualizar
 * o crear un registro en la base de datos.
 *  
 *  La interfaz será implementada en el service usando el @autowired
 */

@Repository
public interface LeagueRepository extends JpaRepository<Leagues, Long> {	
	/**
	 * save(), findOne(), findById(), findAll(), count(), delete(), deleteById()... are autogenerated by JpaRepository
	 * 
	 */
	@Query(value = "SELECT * FROM leagues WHERE id= :id AND name= :name", nativeQuery = true)
	Leagues findLeagueByIdAndName(@Param("id") long id, @Param("name") String name);
}
